### ISSUE TITLE
Reflective calls crash the linker backend

### ISSUE THREAD

**Issue by sjrd** [tanishiking/scala-wasm#71]
See
https://github.com/tanishiking/scala-wasm/blob/038d769069b4c4d4bfffe8d69550eb44c8f9ef1b/build.sbt#L184-L186

**Comment by tanishiking** [comment]
## Problem
For example, the following Scala program will compile to the SJSIR below

```scala
@Test def subtypingInReturnTypes(): Unit = {
  class A { def x: Int = 1 }
  class B extends A { override def x: Int = 2 }

  object Generator {
    def generate(): B = new B
  }

  def f(x: { def generate(): A }): A = x.generate
  assertEquals(2, f(Generator).x)
}
```

SJSIR:

```scala
// def f(x: { def generate(): A }): A = x.generate
private def f$1;Ljava.lang.Object;Lsample.Main$A$1(x: any): sample.Main$A$1 = {
  {
    val x$2: any = x;
    x$2.generate;R() // reflectiveProxy
  }.asInstanceOf[sample.Main$A$1]
}

// x$2.generate;R()
Apply(org.scalajs.ir.Trees$ApplyFlags@0,VarRef(LocalIdent(LocalName<x$2>)),MethodIdent(MethodName<generate;R>),List())
```

The problem in WebAssembly backend is that the `generate` method is not present in the vtable nor itable of any (`java.lang.Object`). We need to find a way to resolve the appropriate `generate;R` method from somewhrere.

## How to tell the `Apply` is a reflective call?
We can identify a reflective call by checking if the `MethodName` has the `isReflectiveProxy` flag set to true.

https://github.com/scala-js/scala-js/blob/95c38be0501fb81c992f3ce8b9e5a9828c2e831e/ir/shared/src/main/scala/org/scalajs/ir/Names.scala#L325-L329

## How to resolve methods?
- 🚫 Can we resolve a method from the vtable at runtime?
  - No, because we cannot determine the specific class's vtable at compile-time (the receiver type is always java.lang.Object for a reflective call).
  - Also, we cannot walk through the vtable to resolve a method at runtime.
- 🚫 Register the reflective proxy methods in the vtable of `java.lang.Object` (or the `table` section of Wasm), and resolve methods from there?
  - There might be a name collision between reflective proxy methods, in which case we cannot uniquely resolve a method.
For example, consider the following case:

```scala
class Generator1:
  def generate(): X = ???

class Generator2:
  def generate(): X = ???

def f(x: { def generate(): A }): A = x.generate

f(new Generator1)
f(new Generator2)
```

In this case, we cannot uniquely resolve the generate method, as both Generator1 and Generator2 have a generate method.

### Maybe solution?

- I'm thinking that we could add another table, adjacent to the itable, to the runtime object (let's call it the `rtable` for the "reflection table").
- The `rtable` would be an array of tuples, where each tuple contains the methodName (as a reference to any object) and a function reference.

```wasm
(type $reflectiveProxy (struct
  (field $name (ref any)) ; method name
  (field $func funcref)   ; function reference
))

(type $rtable (array $reflectiveProxy))
```

- At runtime, if the method is a reflective proxy, we can walk through the `rtable` of the object and find an element that matches the method name.
- If a match is found, we can get the function reference and call it using `call_ref`. If no match is found, we can trap.

Further thinking: how about primitives (hijacked classes)?

**Comment by sjrd** [comment]
> 🚫 Register the reflective proxy methods in the vtable of `java.lang.Object` (or the `table` section of Wasm), and resolve methods from there?
> 
>     * There might be a name collision between reflective proxy methods, in which case we cannot uniquely resolve a method.
>       For example, consider the following case:

This shouldn't be an issue. If they collide, they actually semantically collide, so it's fine to put them in the same vtable slot.

> * I'm thinking that we could add another table, adjacent to the itable, to the runtime object (let's call it the `rtable` for the "reflection table").

This is also a possibility. It trades run-time speed of executing reflective calls for space efficiency of the vtables. This is more complicated to implement, but is also probably the better trade-off. We do not expect reflective calls to be fast (they aren't on the JVM).

If we take this choice we should put the `rtable` pointer inside the `vtable`. We don't want to spend an additional word in every object for something that will be slow anyway.

> Further thinking: how about primitives (hijacked classes)?

Use `jsValueType` to get the `typeData` of the corresponding *representative class*, and follow the `rtable` of the representative class (e.g., `j.l.Double`).

**Comment by tanishiking** [comment]
Thank you very much for the explanation @sjrd 

> This shouldn't be an issue. If they collide, they actually semantically collide, so it's fine to put them in the same vtable slot.

Opps, you're right, when the reflective proxy methods are registered into the vtable of `java.lang.Object` (while it doesn't when we use `table` section though)

- Putting reflective proxy into `j.l.Object`'s vtable
  - **Pros**
    - Easy to implement
    - Reflection calls will be fast, as they will use normal dynamic dispatches
  - **Cons**
    - Every vtable (regardless of whether it contains reflective proxy or not) will be larger and sparse if the program contains a lot of reflective calls. It's unclear how the size of the vtable affects runtime performance or binary size.
- **`rtable` approach:**
  - **Pros:**
    - The vtable size won't be affected, as the `rtable` will be added to the vtable but that's it.
  - **Cons:**
    - Reflective calls will be slower compared to the first approach.

Overall, the `rtable` approach seems nicer as it won't affect the vtable size of all objects, even though it might result in slower reflective calls.

What do you think?

**Comment by sjrd** [comment]
> Overall, the `rtable` approach seems nicer as it won't affect the vtable size of all objects, even though it might result in slower reflective calls.
> 
> What do you think?

Yes, I agree.
